version: '3'

services:
  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     restart: unless-stopped
     ports:
       - "9090:9090"
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
       - prometheus5_data:/prometheus
       - ./prometheus.rule.yml:/etc/prometheus/prometheus.rule.yml:ro
     networks:
       - monitoring_network

  grafana:
     image: grafana/grafana:latest
     container_name: grafana
     restart: unless-stopped
     ports:
       - "3000:3000"
     environment:
       - GF_SECURITY_ADMIN_PASSWORD=admin
       - GF_SECURITY_ADMIN_USER=admin
     volumes:
       - grafana5_data:/var/lib/grafana:rw
     depends_on:
       - prometheus
     networks:
       - monitoring_network

  exporter-mikrotik:
    image: ghcr.io/akpw/mktxp:latest
    container_name: mikrotik-exporter
    ports:
      - "49090:49090"
    volumes:
      - ./mktxp:/home/mktxp/mktxp
    user: 100:101
    depends_on:
       - prometheus
    networks:
       - monitoring_network
  volumes:
    prometheus5_data:
      driver: local
    grafana5_data:
      driver: local

  networks:
    monitoring_network:
      driver: bridge 
