global:
  scrape_interval: 15s
rule_files:
  - "/etc/prometheus/prometheus.rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'mktxp'
    static_configs:
      - targets: ['mikrotik-exporter:49090']
